// src/components/auth/login.component.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AuthService from '../../services/auth.service';
import { useUser } from '../../contexts/user.context';

const Login: React.FC = () => {
  const [credentials, setCredentials] = useState<{ name: string; password: string }>({ name: '', password: '' });
  const [errorMessage, setErrorMessage] = useState<string>('');
  const navigate = useNavigate();

  const { setUser, user } = useUser();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setCredentials({ ...credentials, [name]: value });
  };

  const login = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      const res = await AuthService.login(credentials);
      localStorage.setItem('token', res.data.token);
      localStorage.setItem('isAdmin', res.data.isAdmin);
      setUser({
        employeeId: res.data.employeeId,
        name: res.data.name,
      });
      navigate(res.data.isAdmin ? '/admin' : '/employee');
    } catch (error) {
      setErrorMessage('Invalid credentials. Please try again.');
      console.error('Login error:', error);
    }
  };

  return (
    <div> {/* שים כאן את התג <div> במקום <body> */}
    <div className="development-banner">האתר בשלבי פיתוח</div>
    <br />
    <div className="container mt-5">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card">
            <div className="card-header text-center">
              <h2>התחברות/הרשמה</h2>
            </div>
            <div className="card-body">
              <form onSubmit={login}>
                <div className="form-group">
                  <label htmlFor="name">שם:</label>
                  <input id="name" name="name" type="text" onChange={handleChange} className="form-control" required />
                </div>
                <div className="form-group">
                  <label htmlFor="password">תעודת זהות:</label>
                  <input id="password" name="password" type="password" onChange={handleChange} className="form-control" required />
                </div>
                <div className="d-flex justify-content-center align-items-center mt-3">
                  <button type="submit" className="btn btn-primary me-2">התחבר</button>
                  <p className="my-0 mx-2">משתמש חדש?</p>
                  <button type="button" className="btn btn-secondary ms-2" onClick={() => navigate('/register')}>הירשם</button>
                </div>
                {errorMessage && <div className="alert alert-danger mt-2">{errorMessage}</div>}
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> // עדכן כאן גם
  );
};

export default Login;

// src/modules/auth/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
[x: string]: any;
  credentials = { name: '', password: '' };
  errorMessage: string = '';

  constructor(private authService: AuthService, private router: Router) { }

  ngOnInit(): void {
  }

  navigateToRegister() {
    this.router.navigate(['/register']);
  }

  login() {
    this.authService.login(this.credentials).subscribe(
      (res: any) => {
        // Save token and role info to localStorage
        localStorage.setItem('token', res.token);
        localStorage.setItem('isAdmin', res.isAdmin);

        // Navigate based on user role
        if (res.isAdmin) {
          this.router.navigate(['/admin']);
        } else {
          this.router.navigate(['/employee']);
        }
      },
      (error) => {
        // Handle error
        this.errorMessage = 'Invalid credentials. Please try again.';
        console.error('Login error:', error);
      }
    );
  }
}

<div class="login-container">
    <h2>התחברות/הרשמה</h2>
    <form (ngSubmit)="login()">
      <div class="form-group">
        <label for="name">שם:</label>
        <input id="name" name="name" type="text" [(ngModel)]="credentials.name" required>
      </div>
      <div class="form-group">
        <label for="password">תעודת זהות:</label>
        <input id="password" name="password" type="password" [(ngModel)]="credentials.password" required>
      </div>
      <button type="submit" class="btn btn-primary">התחבר</button>
      <p>משתמש חדש?</p>
<button type="button" class="btn btn-primary" (click)="navigateToRegister()">הירשם</button>

      <div *ngIf="errorMessage" class="error-message">{{ errorMessage }}</div>
    </form>
  </div>
